on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 23 * * *'
    
name: jekyll-goodreads-import

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash ./import-goodreads.sh
    - name: Commit new content
      run: |
        git config --global user.email "martin.knudsen@gmail.com" && git config --global user.name "Martin Knudsen" && \
        git add ./_posts/* && git commit -am "new goodreads content" && git push || echo "Nothing to import."
