on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        echo docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash ./import-letterboxd.sh
    - name: Commit new content
      run: |
        echo "hi, this is a test" >> ./test.md && git config --global user.email "martin.knudsen@gmail.com" && git config --global user.name "Martin Knudsen" && git commit -am "new letterboxd content" && git push

